### ISSUE TITLE
Race in `open_or_create`

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx2#108]
## Required information

When multiple processes are startup concurrently and are creating the same service with `open_or_create` it can happen that all processes detect the service as non-existing.

When then all processes start creating the service, all except one will fail creating the service. A better option would be that the processes that fail creating the service retry to open the service again.

**Comment by Myriade-Medieval** [comment]
I think I have this exact race condition happening. My rust code is called from C with ffi, I fork and then open_or_create in both parent and child. No data is sent, and I get
```
| Unable to open shared memory since the shared memory does not exist
```
and
```
| Failed to open posix_shared_memory::DynamicStorage since a shared memory with that name does not exists.
```

Now, sleeping for one second inside the parent before connecting works fine and those messages are gone.

I'll try to produce a minimal reproduction project, if possible all in rust with nix fork.

**Comment by elfenpiff** [comment]
@Myriade-Medieval on which iceoryx2 version are you working? If the problem is not fixed on iceoryx2 `main` would you mind creating a new bug report and link this issue here as well.

**Comment by Myriade-Medieval** [comment]
With further testing, it seems the issue is coming from my code, apologies
