### ISSUE TITLE
Introduce `Capacity` type

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx2#142]
## (Code) Example Of Cumbersome API

Fixed size containers often have a capacity member variable that is never changed during their lifetime. A custom strong type that can be only set once with `new` and can be read via `Deref` would reflect this in the API.

## Improvement Suggestion

 * [ ] Introduce `Capacity` type in `iceoryx2-bb-elementary`
 * [ ] Use `Capacity` type in every RelocatableContainer, Container

**Comment by elfenpiff** [comment]
@elBoberido I think I would close the issue without fixing it, since such a type would have severe drawbacks.

* If we implement `copy` & `clone` the sole purpose, modify once and never update can be easily circumvented
* If we do not implement them, every container using this type is suddenly also non-copy & non-clonable.

We can implement clone by hand, but loosing copy would be a pity.

**Comment by elBoberido** [comment]
@elfenpiff fine with me
