### ISSUE TITLE
user-defined service properties

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx2#231]
## Brief feature description

Services may have properties that correspond to sensors or other constraints that cannot be represented in the context of iceoryx2. Therefore, the user needs the ability to set user-defined properties.

## Detailed information

```rust
let service = zero_copy::Service::new(&service_name)
  // START: user-defined service properties
    .custom_property("CameraResolution", "1920x1080")
    .custom_property("Framerate", "60")
  // END: user-defined service properties
    .publish_subscribe::<TransmissionData>()
    .open_or_create()?;
```

The user-defined service properties can be read via the services static config:

```rust
let camera_resolution = service.static_config()
                               .custom_property("CameraResolution");
```

**Comment by elBoberido** [comment]
Is the restriction to byte string literals necessary? Why not accept any valid UTF8 string?

**Comment by elfenpiff** [comment]
@elBoberido just to test if you pay attention.
