### ISSUE TITLE
Implement streaming operator for CXX types

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-iceoryx/iceoryx2#330]
## Brief feature description

Some types have implemented a streaming operator to allow the user to print details more easily. The iceoryx_hoofs logger shall support them as well.

## Detailed information

 * [ ] iceoryx2-ffi/cxx/include/iox2/event_id.hpp
 * [ ] iceoryx2-ffi/cxx/include/iox2/static_config.hpp
 * [ ] iceoryx2-ffi/cxx/include/iox2/messaging_pattern.hpp
 * [ ] iceoryx2-ffi/cxx/include/iox2/attribute_set.hpp
 * [ ] check with `rg "operator<<"` if any class is missing.

**Comment by sushanthkumar2004** [comment]
Sorry if I missed something, but aren't the streaming operators for the 4 classes above already there?

**Comment by elfenpiff** [comment]
@sushanthkumar2004 you are completely right. I guess we can close the issue.

Sorry for misleading issue. If you would like to contribute to iceoryx2 I can take a look for another good first issue if you like.

**Comment by sushanthkumar2004** [comment]
Yeah I'd love to help out! @elfenpiff
