### ISSUE TITLE
Header files missing after executing "make install"

### ISSUE THREAD

**Issue by xfsaid** [eclipse-iceoryx/iceoryx2#515]
iceoryx2-ffi/cxx/cmake/install.cmake
```cmake
install(
    # the '/' at the end is important in order to not have the 'include' folder installed but only the content
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/
    DESTINATION ${DESTINATION_INCLUDEDIR}
    COMPONENT dev
)
```
I found that the installation of C++ related header files is here, but there are many missing. For example:
```c++
#include "iox/duration.hpp"
#include "iox/expected.hpp"
#include "iox/log/logstream.hpp"
#include "iox/logging.hpp"
#include "iox/assertions.hpp"
#include "iox/error_reporting/configuration.hpp"
```

I don't know if anyone is completing these. If not, I think I need to complete them myself.

**Comment by elBoberido** [comment]
Those headers come from [iceoryx_hoofs](https://github.com/eclipse-iceoryx/iceoryx/tree/main/iceoryx_hoofs). For ease of use, the iceoryx_hoofs dependency is automatically fetched in developer setups. Please have a look https://github.com/eclipse-iceoryx/iceoryx2/blob/main/iceoryx2-ffi/cxx/README.md on how to use iceoryx_hoofs in a production setup.
